services:
  - type: web
    name: image-uploader
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://yashsolanki1622_db_user:Fguuuml5Lwcj1wsh@cluster0.iolebsr.mongodb.net/
      - key: CLOUD_NAME
        value: dkklnd2k1
      - key: API_KEY
        value: 645396612834928
      - key: API_SECRET
        value: bP8daAr4MXqhfflNI1DtokJ6HYw
